services:
  app:
    container_name: cartaNatal-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - storage:/var/www/html/storage
    ports:
      - "8080:8000"
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_DEBUG: "false"

volumes:
  storage:
