ServerName localhost

<IfModule mpm_prefork_module>
    StartServers 2
    MinSpareServers 2
    MaxSpareServers 4
    ServerLimit 4
    MaxRequestWorkers 4
    MaxConnectionsPerChild 1000
</IfModule>

<Directory /var/www/html/public>
    AllowOverride All
    Require all granted
</Directory>
